### PR TITLE
Feature loading UI

### LINKED ISSUE #220: Loading UI Design
# Description:
We need to design and implement a loading UI component for the creating account process and Login process. The goal is to provide a seamless user experience by displaying a progress bar and a subtitle that informs the user that their request is being processed.
## Acceptance Criteria:
- [ ] The loading UI is displayed immediately after the user submits the form.
- [ ] The loading UI includes a progress bar that animates to indicate that the account creation process is in progress.
- [ ]  a subtitle that says "Creating an account, please wait".
- [ ] The loading UI is displayed for a reasonable time (e.g. 2-3 seconds) before the user is redirected to the next step.

**Dependency:** _This issue is dependent on the completion of the "Implement Sign up UI Design for Web #216"  and " Implement Web Login UI design #219 " issues. The loading UI will be displayed after the user submits the sign-up form, so the sign-up UI must be designed and implemented first._

**Note:** _For now, we're only focusing on creating the design UI for mobile view. We'll address the desktop view in a future iteration._

Image

Logging in

Some hints:

Please read our [readme](https://github.com/Greenstand/treetracker-wallet-app) for more information/guide/tutorial.
For design guidelines checkout our [Figma design](https://www.figma.com/design/UjbBQIFKATd1DisTBRsMdd/Test-Project?node-id=29-9854&t=9h97AC3WcxkziHnS-0)
Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
To know more about our organization, visit our [website](https://greenstand.org/).
If you want to join the slack community (some resources need the community member's permission), please leave your email address.

### PR DESCRIPTION
**Pull request by Lorenabelo**
# Description

In this PR only the component called loading has been created, so that it can be implemented in the login and sign up screens.

## Type of change
resolves #220 

[comment]: # 'Please delete options that are not relevant.'

[x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

[x] I have performed a self-review of my own code
[ ] I have commented my code, particularly in hard-to-understand areas
[ ] I have made corresponding changes to the documentation
[ ] My changes generate no new warnings
[ ] I have added tests that prove my fix is effective or that my feature works
[ ] New and existing unit tests pass locally with my changes
[ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by dadiorchen — COMMENTED** [review]
@Lorenabelo thanks for you contribution!
If the issue is about creating a single component, I suggest we create component test with Cypress to cover it, @pierrelstan what do you think?

**Comment by pierrelstan** [comment]
> @Lorenabelo thanks for you contribution! If the issue is about creating a single component, I suggest we create component test with Cypress to cover it, @pierrelstan what do you think?

I agree @dadiorchen,  it is a good idea to test it.

**Comment by Davidezrajay** [comment]
@pierrelstan can you guide @Lorenabelo though what needs to happen to merge this request?

**Comment by pierrelstan** [comment]
@Davidezrajay Will do! It just needs an update with the latest changes from the main branch.

**Review by pierrelstan — APPROVED** [review]

**Pull request merged**
