### PR TITLE
feat: home navbar

### PR DESCRIPTION
**Pull request by yuriBaza23**
### Description
This PR describes the addition of a navigation bar to the "home", "send" and "settings" screens. This change required changing the layout files and creating files for each screen.

**Resolves**: #268 

---

### Changes Made
- [ ] Changes in **`apps`** folder (specify the app and briefly describe the changes):
  - [ ] `Web`
  - [x] `Native` Changes to layout files and creation of files for the "home", "send" and "settings" screens

- [ ] Changes in **`packages`** folder (specify the package and briefly describe the changes):
  - [ ] `Core`

---

### Type of Change
- [ ] 🐛 **Bug fix** (non-breaking change which fixes an issue)
- [x] ✨ **New feature** (non-breaking change which adds functionality)
- [ ] 💥 **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 **Documentation update** (changes)

---

## Screenshots
|       Before        |       After        |
| :-----------------: | :----------------: |
| Screenshot 2024-11-08 at 00 43 00 |  Screenshot 2024-11-08 at 00 41 31 |
| Screenshot 2024-11-08 at 00 43 00 |  Screenshot 2024-11-08 at 00 41 42 |
| Screenshot 2024-11-08 at 00 43 00 |  Screenshot 2024-11-08 at 00 42 03 |
---

### How Has This Been Tested?
- [ ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests
- [x] Manual

---

### Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

---

### Additional Comments
If I find anything that needs changing, please let me know.

### CODE REVIEW

**Comment by pierrelstan** [comment]
@yuriBaza23, Could you kindly resolve the merge conflicts?

**Comment by yuriBaza23** [comment]
@pierrelstan Hello, Ready. Now the conflicts are resolved.

**Comment by pierrelstan** [comment]
Thank you for your work, @yuriBaza23 ! Could you share your email so I can invite you to Slack?

**Comment by yuriBaza23** [comment]
> Thank you for your work, @yuriBaza23 ! Could you share your email so I can invite you to Slack?

I'm glad you liked the work. My email is yurisbaza@gmail.com

**Comment by pierrelstan** [comment]
Hi @yuriBaza23, I noticed some conflicts in the branch. When you get a chance, could you help resolve them? I appreciate it!

**Review by pierrelstan — APPROVED** [review]

**Pull request closed without merging**
